### ISSUE TITLE
[Meta] pdf handling

### ISSUE THREAD

**Issue by mjourdan** [openpaperwork/paperwork#655]
(This ticket is here to keep track of all pdf related issue)

## Description

We have a number of ticket to improve the UX while dealing with pdf documents. The goal is to make paperwork a more-than-decent document reader.

## Issues

Importing pdf:

- [ ] [PDF Import: automatically figure out the date of the document](#338)
- [ ] [Gracefully handle encrypted PDF](#384)
- [ ] [Allow pdf manipulation](#495)

Supporting pdf's basic features:

- [ ] [Display PDF title or first few additional keywords in documents list.](#623)
- [ ] [PDF: Table of content](#76)

Later:

- [ ] [Document properties](#252)
- [ ] [tagged pdf](#244)

**Comment by mjourdan** [comment]
Please find [experimental wireframes to import pdf](https://raw.githubusercontent.com/mjourdan/gnome-design/master/paperwork/experiments-2.0/add-paper-import-from-file.png). This should cover all of the issues above (except #244).

**Comment by jflesch** [comment]
Hm, regarding unencrypted PDF files, I don't feel at ease with asking password every time the user wants to open it. Looks like a nice source of bugs :/

**Comment by jflesch** [comment]
However, the password could be stored unencrypted besides the PDF files (in which case, it's up to the user to secure all their papers).

**Comment by tido-** [comment]
If you face a complex problem, break it down into smaller pieces, leave exceptions away (encrypted) file.
Same is true for "Allow pdf manipulation" leave exceptions away, the tool is made for scanning.

So you can focus on reading out the metadata of the PDF-Document. 
Date, if US- or European-format, does it differ?
Title, keywords or table of content - if the PDF is just the container for a scanned document, how would this turn out?
