### ISSUE TITLE
[Meta] scanner handling

### ISSUE THREAD

**Issue by mjourdan** [openpaperwork/paperwork#660]
(This ticket is here to keep track of all scanner related issue needing ux improvement) 

## Description

Most scanners offer to scan only one page at a time (flatbed), while some allow to scan a bunch of pages at once (flatbed). A few even support scanning recto & verso. The GUI should provide the user with options relevant to the device in use.

## Issues

- [] Two-sided scanning #535
- [] "Scan from ADF" (batch mode) should support source selection (duplex) #554
- []  Merge recto and verso pages #579

**Comment by mjourdan** [comment]
Some experiments here:

- [scan from flatbed](https://raw.githubusercontent.com/mjourdan/gnome-design/master/paperwork/experiments-2.0/add-paper-scan-from-flatbed.png)
- [scan from feeder](https://raw.githubusercontent.com/mjourdan/gnome-design/master/paperwork/experiments-2.0/add-paper-scan-from-feeder.png)

That's open for comments.

**Comment by jflesch** [comment]
Just one comment : I don't think the part where the label list appear from the right is really relevant. In a perfect world, label should be automagically guessed correctly. Also, currently they appear on the left side .. :/

**Comment by mjourdan** [comment]
> Just one comment : I don't think the part where the label list appear from the right is really relevant. In a perfect world, label should be automagically guessed correctly. Also, currently they appear on the left side .. :/

Thanks for this comment. Even in a perfect world, the user would have to create & edit tags before paperwork is able to automatically associate them with papers. So the question is: why moving the pane from the left to the right? I see 2 reasons to do so.

1. I am not aware of software other than Paperwork that would show the properties of a document on the left of it. Activating a "details" button to have file properties/metadata displayed in a right pane seems a more common pattern. Some examples here: [Nextcloud](https://nextcloud.com/wp-content/themes/next/assets/img/features/comments.png?x16328), [plus.google.com](https://plus.google.com/photos/photo/112026213399155142823/6457160520245376978?icm=false), [Bear](http://help.shinyfrog.net/discussions/bear/29/assets/607fa8b090eaee5ac958b9dcf5c63bcfb01cea0c/thumb/12.35.59_PM.png)...

2. As we are adding new features (overview, export queue, saved searches...) we need to keep things simple. What we did in the latest wireframes experiments is to split the interface in a serie of vertical panes. The idea is to build a simple workflow, going from the general (left) to the specific (right). This is [illustrated here](https://raw.githubusercontent.com/mjourdan/gnome-design/master/paperwork/experiments-2.0/layout-left-to-right-workflow.jpeg) and [there](https://raw.githubusercontent.com/mjourdan/gnome-design/master/paperwork/experiments-2.0/3-columns-layout-switching.png).

**Comment by tido-** [comment]
> scan from feeder

Why is it necessary to tell the application how many pages it has to scan? 
Doesn't the device report the end/last page - can I help by reading out some logs?
With regard to **automagically**, paperwork would serve me one-page-after-the-other and either I 'accept' paperworks Label suggestion "a tick to click" or I click 'Edit'.

PS: 3-column layout with 16:10 monitor makes sense to me. Having properties on the right as well.

**Comment by jflesch** [comment]
Actually, I'm considering removing the whole dialogs, and just assume that the user has put 1 document in the feeder:
- If "New document" is selected --> it creates a new one.
- If another document is selected --> it appends the pages.
 
It would make the behavior pretty much consistent with when we scan single pages.

**Comment by tido-** [comment]
> 1 document in the feeder

What was the reason for this dialog in the first place? Which problem did it solve?

If you throw three invoices on the ADF, 1 page, a 2 page'r and a 3 page'r.
I play your scenario, but instead of 'another' I would call it 'additional':
1 page = click New Document
2 pages = click New Document (recto), additional (verso)
3 pages = click New Document (recto), additional (recto), additional (verso)
now the scanner sends: end/last page

**Comment by jflesch** [comment]
> What was the reason for this dialog in the first place? Which problem did it solve?

It was mostly focused on first time users : They usually have a lot of documents to scan --> they take 10 documents, put it in the scanner, configure the mutli-scan dialog, launch the process, and go take a coffee.
But frankly, it seems now like a poor idea. It would actually be much simpler to just scan pages until the feeder is empty.
